### ISSUE TITLE
Align language coverage with Java and VDMTools generators

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#108]
For the purpose of a more fair comparison of generators we should endeavour to increase language coverage of VDM2C to approach that of the other two generators.  Comparison is more fair this way because the generators can be seen to be equally generic.

**Comment by bandurvp** [comment]
Constructs to implement for now:
- [x] precondition checks (PJ, VPB)
- [x] map iteration + GC version (PJ)
- [x] Support map iteration in the code-generation platform (PJ)
- [x] map iteration (VPB), signature:  `TVP vdmMapIterate(TVP map, TVP num)`
- [x] map composition + GC version (e.g. {2 |-> 3} comp {1 |-> 2}) (PJ)
- [x] Support map composition in the code-generation platform (PJ)
- [x] map composition (VPB), signature:  `TVP vdmMapCompose(TVP a, TVP b)`  to correspond to `a comp b` in VDM.
- [x] iota (PJ)
- [x] Support iota in the code-generatoin platform (PJ)
- [x] Emit `VdmClassHierarchy.h` 
- [x] Emit `NO_INHERITANCE` in `VdmModelFeatures.h` (PVJ)
- [x] nondeterministic statement `||` (PJ)
- [x] Support the nondeterministic in the code-generation platform (PJ)
- [x] exists1 quantifier (PJ)
- [x] isofbaseclass (VPB), signature:  `TVP isOfBaseClass(TVP val, int baseID)`
- [x] isofbaseclass (PJ)
- [x] Address issue with isofbaseclass in the runtime and enable generator tests, see https://github.com/overturetool/vdm2c/issues/108#issuecomment-337886061
- [x] isofclass + GC version (VPB), signature:  `TVP isOfClass(TVP val, int classID)`
- [x] isofclass  + GC version (PJ)
- [x] Address issue with isofclass in the runtime and enable generator tests, see https://github.com/overturetool/vdm2c/issues/108#issuecomment-337886061
- [x] samebaseclass  + GC version  (VPB), signature:  `TVP sameBaseClass(TVP a, TVP b)`
- [x] samebaseclass  + GC version (PJ)
- [x] Address issue with samebaseclass in the runtime and enable generator tests, see https://github.com/overturetool/vdm2c/issues/108#issuecomment-337886061
- [x] sameclass  + GC version  (VPB), signature:  `TVP sameClass(TVP a, TVP b)`
- [x] sameclass  + GC version  (PJ)
- [x] Address issue with sameclass in the runtime and enable generator tests, see https://github.com/overturetool/vdm2c/issues/108#issuecomment-337886061
- [x] Support isofbaseclass, samebaseclass and sameclass in the code-generation platform
- [x] emit `NO_IS` flag in `VdmModelFeatures.h` (PJ)
- [x] `is_(...)` + GC version VPB
- [x] `is_(...)` + GC version PVJ
- [x] Support `is_(...)` for union types as explained in https://github.com/overturetool/vdm2c/issues/108#issuecomment-336045911 (PJ)
- [x] Full support for `is_(...)` in the code-generation platform (PJ)
- [x] increase `is_` coverage for basic types (VPB), generator to emit the following (PJ), plus their GC versions:
   - [x] `isNat` PJ
   - [x] `isNat` VPB
   - [x] `isNat1` PJ
   - [x] `isNat1` VPB
   - [x] `isInt` PJ
   - [x] `isInt` VPB
   - [x] `isReal` PJ
   - [x] `isReal` VPB
   - [x] `isBool` VPB
   - [x] `isBool` PJ
   - [x] `isRat` PJ
   - [x] `isRat` VPB
   - [x] `isChar` PJ
   - [x] `isChar` VPB
   - [x] `isToken` PJ
   - [x] `isToken` VPB

**Comment by bandurvp** [comment]
Need to include support for answering the inheritance queries `isofbaseclass`, `isofclass`, `samebaseclass`, `sameclass`.  This must take the form of an array of `int` included in `Vdm.h`.  Assume the inheritance hirarchy (child -> parent) B -> A, C -> A, D -> C.  The array would look like the following:
```
#include "A.h"
#include "B.h"
#include "C.h"
#include "D.h"

int assoc[] = {CLASS_ID_B_ID, CLASS_ID_A_ID, CLASS_ID_C_ID, CLASS_ID_A_ID, CLASS_ID_D_ID, CLASS_ID_C_ID};
```
If the model contains no inheritance, then the file containing this information will simply contain an empty array:
```
int assoc[] = {};
```
This file must be paired with a corresponding flag `NO_INHERITANCE` in the `VdmModelFeatures.h` file.

**Comment by peterwvj** [comment]
Thanks, Victor. Did you really mean `Vdm.h`? I mean, the array is generated.

**Comment by bandurvp** [comment]
Good point, sorry about that!  Because it's also generated, maybe it should follow the same approach as the `VdmModelFeatures.h` file.  We could name it `VdmClassHierarchy.h`

**Comment by peterwvj** [comment]
Yeah sounds good.

**Comment by bandurvp** [comment]
@peterwvj I have a questiona bout the `isSeqOf...` and `isSetOf...` queries I introduced above.  Would it not be a better idea to implement generic `isSet` and `isSeq` queries in the runtime and have the generator generate the right structure of calls to these plus `isInt` etc. for model queries such as `is_([[[3]]], seq of seq of seq of int)`?  It would keep the runtime smaller, plus it would allow any kind of nesting in the VDM model, things like as `is_([{'c'}], seq of set of char)`.

**Comment by bandurvp** [comment]
After discussion, we will implement a static and recursive mechanism in the runtime supporting arbitrary nesting of `seq` and `set` for built-in types.

Signature of the function should be `is(TVP value, char nested_type[])`.

Encoding scheme for `nested_type` to follow shortly.

**Comment by bandurvp** [comment]
@peterwvj , let us try to use the following convention for identifying the nested type.  A 'q' for `seq of`, a 't' for `set of` and a 'z' at the end to signify the end of the nested type.  So the query `is_(e, seq of set of nat)` would result in `char nested_char[] = {'q', 't', 'z'};` that is passed to the `is` function.

**Comment by peterwvj** [comment]
Sounds good to me, Victor. Shouldn't `is` also handle basic types (`nat`, `nat1`, `char`, `rat`, `bool` `int`, `token`, `real`) which form the base cases of `is`. I mean, in the above example it looks like the char array is missing the `nat` type. So assuming that `n` identifies `nat` and `z` terminates the array I would expect:

- `seq of set of nat` to be encoded as `q`, `t`, `n`, `z`
- `nat` to be encoded as `n`, `z`
- `set of nat` to be encoded as `t`, `n`, `z`
- etc.

Is that what you had in mind?

How does this encoding scheme deal with records?

**Comment by bandurvp** [comment]
Hi Peter, no, what I had in mind is that the inner type would be passed in the `inner_type` parameter as, in this case, `VDM_NAT`.

Regarding products, I liked your convention of identifying character followed by number of fields, I'll work a bit with that and maybe we can have another chat once I wrap my head around it entirely.

**Comment by bandurvp** [comment]
I would like to use a list like the following in the type encoding array.  Many of the built-in types are taken from gcc C++ name mangling:

-  `int`:  'i'
-  `nat`:  'j'
-  `real`:  'd'
-  `bool`:  'b'
-  `char`:  'c'
-  `nat1`:  'k'
-  `rat`:  'e'
-  `token`:  't'
-  `seq of`:  'Q'
-  `seq1 of`:  'Z'
-  `set of`:  'T'
-  `set1 of`:  'Y'
-  product:  'P'
-  record:  'R'
-  map:  'M'
-  class:  'W'

Each one of these is prepended with a character `'0'` if the type is optional, or a character `'1'` if the type is not optional.

I have worked out and tested the following scheme for encoding the type of the expression being queried, and it works well.

-  Class type encodes as `{opt, 'W', classID}`.  When this array is generated, the `classID` can be the `CLASS_ID_XXX_ID` define corresponding to that class definition.
-  Record type encodes as `{opt, 'R', recID}`.  Same idea for the `recID` as `classID` above.
-  Product types are the more complicated recursive ones.  The scheme I'm using is the following:

```{opt, 'P', numOfFields, '*', opt1, field1Type, '*', opt2, field2Type, '*', ..., '*', optn, field(numOfFields - 1)Type, '*'}```

With this scheme, the runtime function `is` only needs two parameters:  `is(TVP e, char type_encoding[])`.
- Map types are the same as records, only the `numOfFields` field is missing, since this is always 2:

```{opt, 'M', '*', opt1, field1Type, '*', opt2, field2Type, '*'}```

Some examples:
-  `seq of int`:  `{'1', 'Q', '1', 'i'}`
-  `seq of [int]`:  `{'1', 'Q', '0', 'i'}`
-  `[seq of int]`:  `{'0', 'Q', '1', 'i'}`
-  `seq of seq of int`:  `{'1', 'Q', '1', 'Q', '1', 'i'}`
-  `seq of set of char`:  `{'1', 'Q', '1', 'T', '1', 'c'}`
-  `int * int`:  `{'1', 'P', 2, '*', '1', 'i', '*', '1', 'i', '*'}`.  Notice that the number of fields is the number `2`, not the character `'2'`.
-  `int * (int * [char])`:  `{'1', 'P', 2, '*', '1', 'i', '*', '1', 'P', 2, '*', '1', 'i', '*', '0', 'c', '*', '*'}`
-  `(int * char) * int`:  `{'1', 'P', 2, '*', '1', 'P', 2, '*', '1', 'i', '*', '1', 'c', '*', '*', '1', 'i', '*'}`
- `map int to seq of char`:  `{'1', 'M', '*', '1', 'i', '*', '1', 'Q', '1', 'c', '*'}`

**Comment by peterwvj** [comment]
Sounds good, Victor, thanks!

**Comment by bandurvp** [comment]
@peterwvj I've added precondition checking support to this issue because we need it to align with VDMT, but also because it seems like a very good idea in light issues found with the generated Continental model.

**Comment by bandurvp** [comment]
Hi @peterwvj , in working on the assertions issue I realized that we don't support composition and iteration for maps, but VDMT does.  I've added these to the list above.

**Comment by peterwvj** [comment]
Hi @bandurvp. I've updated the "Constructs to implement for now" list to contain the OO check operations (e.g. sofbaseclass) as well as the tasks concerning emitting the `VdmClassHierarchy.h` file and NO_INHERITANCE flag, which are now supported by the generator. Once the OO check operations are implemented in the runtime I will go ahead and update the generator to emit calls to these functions.

**Comment by bandurvp** [comment]
Hi @peterwvj , I've updated the comment above with the type encoding scheme.  Please let me know what you think and whether it's a good way to go from the point of view of your side of the generator.  For my side it works well.

**Comment by peterwvj** [comment]
Hi @bandurvp . The encoding scheme looks good. I only have one question. Why are the "*"s needed in the encoding of products, e.g. int * int: `{'P', 2, '*', 'i', '*', 'i', '*'}`. Why not just emit `{'P',2,'i','i'}`?

**Comment by bandurvp** [comment]
Hi @peterwvj , it has to do with passing the array onward in the recursive call.  Without the `'*'` separators it would be very complicated to work out which parts of the array to pass on when the type is not as simple as `int * int`, but more complicated, like `(int * nat) * (set of int)`, for instance.  It would essentially require a parser for the encoding language.  The asterisks make the language extremely simple.  Figuring out a good answer to this question, I came across another example that you might find useful, involving double `'*'`s, I've added it above.

**Comment by peterwvj** [comment]
Good, makes sense, thanks for your response. I'll try to work out a visitor that translates VDM types into the proposed C encoding.

**Comment by bandurvp** [comment]
OK @peterwvj , I think I have added support in the runtime for all the OO constructs we discussed in this issue.  I haven't added runtime tests because it's not so easy to do for classes, so I'll just wait for the generator tests to validate the implementations.

**Comment by bandurvp** [comment]
Hi @peterwvj , regarding precondition checks, if they're already supported in the Java generator, then we can follow that mechanism.  Otherwise, I was thinking one way to do it is to emit the precondition check as a separate function, then use the `assert(...)` statement at the beginning of the body of the corresponding function or operation.  Say `op` has precondition `pre_op`, where the implementation of `pre_op` returns a simple `bool`, not a `TVP`.  Then the `assert` call would be a simple call `assert(pre_op());` after all the declarations of the function/operation body.

**Comment by peterwvj** [comment]
Yeah I agree. Adding support for it in the generator should be fairly simple. I think the main bulk of the work is adding the necessary UI part (CLI + GUI) that enables the user to enable/disable precondition generation.

**Comment by peterwvj** [comment]
@bandurvp something just crossed my mind: the type encoding scheme above does not consider the `set1` and `seq1` type constructors.

**Comment by peterwvj** [comment]
@bandurvp In addition to that, the encoding scheme is also missing `map`.

**Comment by bandurvp** [comment]
Good spot @peterwvj , I'll add those now.

**Comment by bandurvp** [comment]
Hi @peterwvj , I've just pushed `is` support for `seq1`, `set1` and `map`.

**Comment by peterwvj** [comment]
@bandurvp Also the type encoding scheme is missing optional types.

**Comment by bandurvp** [comment]
@peterwvj , conceptually there is an enromous overlap between queries on optional and non-optional types.  I don't immediately see a difference between, for example, `is_(3, [int])` and `is_(3, int)` from the point of view of the generated code.  The only case that bears consideration is that of `nil`, as far as I can see.  Is it ever the case that an expression will actually evaluate to `nil`?  Or can it be determined statically whether an `is_` query is being carried out on a `nil`?  I'm asking because maybe we can just consider this case separately.

**Comment by peterwvj** [comment]
@bandurvp 

That's exactly what it means, yes: `n` is of type `[nat]` iff `n = nil or is_nat(n)`. Or generally speaking:

`is_(v, [T]) == v = nil or is_(v, T)`

Generally speaking, it cannot be decided statically whether an expressions evaluates to `nil`. For example, one can easily construct an operation (say `possiblyNat`) that returns either a natural number or `nil`, i.e. the operation has the return type `[nat]`. Therefore `is_nat(possiblyNat())` sometimes evaluates to `true`, and sometimes it evaluates to `false`.

I'm pretty sure the encoding must take this into account somehow, perhaps by preceding optional types with `'O'`. For example, `nat1` would be encoded as `{'O', 'j'}`. Then if you see `'O'` you just check for `NULL` and apply the `is_` function recursively, according to `is_(v, [T]) == v = nil or is_(v, T)`.

Do you think that would work?

**Comment by bandurvp** [comment]
Hi @peterwvj , that sounds very good.  Is it easier for you to prepend or append the `0` to the type:  {`0`, 'j'}` or `{'j', '0'}`?

**Comment by peterwvj** [comment]
@bandurvp Sounds good. When you have sorted out the encoding scheme for optional types, could you update the description above accordingly?

**Comment by bandurvp** [comment]
@peterwvj , of course, will do.  So which one of the two is easier for you?

**Comment by peterwvj** [comment]
Oh, sorry, missed your question :) I would go with prepend, since that reflects the order of the checks (i.e. `v = nil or is_(v, T)`) but either approach will do.

**Comment by bandurvp** [comment]
@peterwvj , OK prepend it is!

**Comment by bandurvp** [comment]
Hi @peterwvj , I've just pushed support for optional types in accordance with the scheme above.  As usual, it's in vpb/development.

**Comment by peterwvj** [comment]
Hi @bandurvp. Just found out that the type encoding scheme isn't covering union types

**Comment by bandurvp** [comment]
Hi @peterwvj , I was thinking about that too.  I think to add support in the runtime we would have to augment TVP, which would increase the binary size dramatically.  Could we alternatively emit a conjunction of `is_` queries based on the constituent types of the union type?  For instance, `is_(3, int | bool) iff is_(3, int) || is_(3, bool)`, so we could emit the corresponding query `vdmOr(is_(3, int), is_(3, bool))`?

**Comment by bandurvp** [comment]
Hi @peterwvj , could we also emit a `NO_IS` flag such that I can cut out all of the type query mechanism if there are no `is` expressions in the model?  This does not cover the OO type queries, as they fall under the `NO_INHERITANCE` flag.

**Comment by peterwvj** [comment]
Regarding both comments (handling of union types + emitting the `NO_IS` flag), sure, sounds like a good plan! I've updated the task lists accordingly.

**Comment by bandurvp** [comment]
Great, I'll put in support for `NO_IS` now.

**Comment by bandurvp** [comment]
Just a comment, the `sameclass` query should also fall under the `NO_IS` category, even though there is no "is" in it.  But `samebaseclass` would fall under `NO_INHERITANCE`.

**Comment by peterwvj** [comment]
Preconditions, which are now supported, are emitted as regular C functions and called in the following way:

```C
TVP preRes_1 = CALL_FUNC_PTR(A, A, this, CLASS_A__Z17pre_opEV);
assert(toBool(preRes_1) && "Precondition failure: _Z17pre_opEV");
vdmFree(preRes_1);
```
There's only one catch: currently, they are only supported in the command-line interface using the `-pre` argument. Obviously we can add GUI supported for this as well, but since that does not have anything to do with aligning language coverage, I'll consider this task done for now. In case we want GUI support, we can create a separate issue for this.

**Comment by peterwvj** [comment]
@bandurvp After thinking about this, I don't think the approach to handling of union types is sufficient. The way I see it, problems occur when you start "embedding" union types into other type constructors (say products), which mixes up the two approaches to checking types. For example, how should we translate checks such as `is_(v, nat * (bool | char))` (v is a tuple where the first field is a natural number, and the second field is either a boolean or a character)? I mean, the runtime cannot confirm that v is a valid tuple value since it cannot check that the second field is of the right type. The way I see it the type encoding scheme must be able to cope with union types, but that require changing the TVP (like you said). One way would be to carry the type encoding in the TVP such that a TVP that represents a value of type `seq of [int]` carries `{'1', 'Q', '0', 'i'}` and so on.

What do you think?

**Comment by peterwvj** [comment]
It looks like the example (and I quote) `int * (int * [char]): {'1', 'P', 2, '*', '1', 'i', '*', '1', 'P', 2, '*', '1', 'i', '*', '0', 'c', '*'}` is missing an `*` at the end of the array. Since tuples are terminated using `*` and this is an example of a tuple containing a tuple as the second field I think that the array should end with `'c','*','*'}`. @bandurvp please confirm that this example contains a typo in the encoding.

**Comment by peterwvj** [comment]
@bandurvp I updated the generator to emit the OO operators (isofbaseclass, isofclass, samebaseclass and sameclass), but I've found runtime related problems with all of them that I need your help to address. Since there's quite a lot of stuff going on, I recommend we sit down face-to-face so I can explain you what's up. My work is available in pvj/ovt-254. However, since I build against Overture 2.5.4-SNAPSHOT (a version which is not released) my build environment is slightly complicated, so I don't recommend you merge this branch.

I've set up numerous tests, inspired by the OO operator examples in the [LRM](http://raw.github.com/overturetool/documentation/master/documentation/VDM10LangMan/VDM10_lang_man.pdf) that demonstrate all of these issues. Currently, I've commented out these tests since they produce code that either does not compile or generate wrong results when executed.

**Comment by bandurvp** [comment]
@peterwvj , regarding https://github.com/overturetool/vdm2c/issues/108#issuecomment-337563814 , yes it is a typo, I've updated the comment, sorry about that.

**Comment by bandurvp** [comment]
Hi @peterwvj , let us talk about the OO operator issues above tomorrow, if you have time.

**Comment by peterwvj** [comment]
Sure, let's talk tomorrow!

**Comment by bandurvp** [comment]
@peterwvj , regarding union types, could we make use of the following type of equivalence to just emit a combinatorial `is` query?  For example, it seems that  `is_(v, nat * (bool | char))` would be equivalent to `is_(v, nat * bool) or is_(v, nat * char)`.  This would require no extension to the runtime, only execution overhead.  I think this would be much better because augmenting TVP with extra type information would result in a huge increse in heap usage.

**Comment by peterwvj** [comment]
Perhaps that's a better approach yes, but like you say, it could in theory increase the number of `is_` calls drastically. I would like to discuss this approach a bit more tomorrow before I start to implement it.

**Comment by peterwvj** [comment]
@bandurvp It looks like `isGC` is missing in the header files.

**Comment by peterwvj** [comment]
I just added `isGC` to the header file in `pv/ovt-254` in order to make the GC tests pass.

**Comment by peterwvj** [comment]
`is*` checks are now implemented. Below is an example that demonstrates how to check if a value is of type `nat * (bool | char)`. Also note that the expression being checked is extracted to a temporary variable in case it has side-effects.

VDM:
```
public isTupPos : () ==> bool
isTupPos () ==
  return is_(mk_(1, 'a'), nat * (bool | char));
```
Corresponding C:
```
static  TVP _Z8isTupPosEV(IsTestCLASS this)	{
  TVP isExpSubject_3 = newProductVar(2, newInt(1), newChar('a'));
  char isExpEncoding_3[] = {'1','P',2,'*','1','j','*','1','b','*'};
  char isExpEncoding_4[] = {'1','P',2,'*','1','j','*','1','c','*'};
  TVP ret_22 = vdmOr(is(isExpSubject_3, isExpEncoding_3), is(isExpSubject_3, isExpEncoding_4));
  return ret_22;
}
```
